name = "coffee-thing"
main = "src/index.ts"
compatibility_date = "2026-05-01"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "coffee.lindsey.fyi"
custom_domain = true

[assets]
directory = "./public"
binding = "ASSETS"
html_handling = "auto-trailing-slash"

[[d1_databases]]
binding = "DB"
database_name = "coffee-thing-db"
database_id = "5fe4ecc7-a751-4625-85ad-66b86183d013"
